title: Periurbania
description: Blogue de Xeografía
author: "Ícaro Obeso Muñiz"


theme: minima

# Minima social links
github_username: icaroviedo
linkedin_username: icaroviedo
mastodon_username: https://mastodon.social/@icaroviedo
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
